title: Signed Networks in Social Media
description: Predicting interactions using signed social networks
author: ADA - EPFL - Romain Gros, Balz Marty & Jimmy Wilde
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
